### ISSUE TITLE
Integer arithmetic in a compiled model wraps silently at 64 bits

### ISSUE THREAD

**Issue by fumitoh** [fumitoh/modelx-cython#52]
Filing this as a reminder; it is pre-existing and not urgent.

mx2cy types an integer cells as C `long long` from the values the sample run traces. Every C integer operation in the compiled model then wraps silently on overflow, where the pure-Python model would have produced an arbitrary-precision result. The compiled model returns a different number, with no warning and no exception.

## Reproduction

```python
def big(t):  return 4000000000
def prod(t): return big(t) * big(t)
def ten(t):  return 10
def ipow(t): return ten(t) ** 20
```

translates to

```python
def _f_prod(self, t: _mx_cy.longlong) -> _mx_cy.longlong: return self.big(t) * self.big(t)
def _f_ipow(self, t: _mx_cy.longlong) -> _mx_cy.longlong: return self.ten(t) ** 20
```

and after `mx2cy Ovf_nomx --sample sample.py --no-spec`:

```
prod  python=16000000000000000000   cython=-2446744073709551616
ipow  python=100000000000000000000  cython=7766279631452241920
```

`prod` does not merely lose magnitude, it changes sign. The wrapped value is stored in the cells cache and returned to Python as an ordinary `int`.

The operands have to come from cells rather than from literals: a large integer literal can send the expression down `PyNumber_Add` on Python objects instead, which stays exact.

## Scope

* `+`, `-`, `*` and `**` on two C-typed integers, in a **cached** cells. Uncached cells stay `object`-typed and keep Python semantics.
* It is not confined to integer-returning cells. `**` between two C integers goes through `__Pyx_pow_PY_LONG_LONG` even inside a `-> double` cells, so `base(t) ** 2` with `base(t)` around 4e9 returns a negative double. The first base that wraps is exactly `3037000500` = `math.isqrt(2**63 - 1) + 1`.
* Not reachable through a cells *parameter*: a cached cells caps its own parameter with the array bound and raises `IndexError` beyond it. The overflowing value has to arrive from another cells.
* Unrelated to #49 / #50. The `**` rewrite added there only touches powers whose exponent is provably floating; every integer power is emitted exactly as modelx exported it, and the generated C for one is byte-identical before and after.

### Cython's `overflowcheck` directive

Adding `"overflowcheck": True` to the generated `setup.py` turns the checked operations into ones that raise `OverflowError: value too large`, with a traceback naming the formula line. The failing cells is not cached, so a retry raises again rather than returning garbage.

Cheaper than expected: on lifelib BasicTerm_S (10,000 model points) and TradLife_A it costs **nothing measurable** — best-of-N within 1%, below this machine's 3-4% run-to-run spread — and about **3%** on a purpose-built model whose formulas are nothing but C integer arithmetic. A synthetic arithmetic-dense loop does show ~4x, but only because the C compiler can otherwise reassociate and strength-reduce the whole chain; a real model's opaque cells calls prevent that optimisation in both builds.

But it does not close the hole and it is not a drop-in:

* It covers binary `+`, `-`, `*` and `<<`. It **misses `**`** — the `__Pyx_pow_PY_LONG_LONG` call sites are byte-for-byte identical with and without it — and also misses unary `-`, `//` and `%`.
* **It can break the build.** Any integer-typed cells containing `abs(<other cells>(t))` fails to compile with Cython 3.2.4: the emitted C contains a literal `None` (`if (unlikely(None == __PYX_MIN(PY_LONG_LONG)))`) and MSVC rejects it with `error C2065: 'None'`. The same tree compiles fine without the directive. `abs()` is not rare in actuarial formulas.
* `overflowcheck.fold` makes no observable difference; it only decides whether the flag is checked once per expression or after each sub-operation.

Separately, `//` and `%` at `LLONG_MIN / -1` kill the process outright with `STATUS_INTEGER_OVERFLOW` (0xC0000095) and no Python traceback, with or without the directive. Narrow, but nasty.

### Rewriting integer `**` through `_mx_sys._mx_pow`

The helper #50 added could also take integer powers in a `-> double` cells, which would fix the magnitude (`ten(t) ** 20` gives `1e20` instead of a wrapped integer) at no precision cost, since the result is stored in a double either way. Two problems: it makes that operation about **11x slower** (1.20 -> 12.93 ns for `t ** 2`, an `imul` becoming a libm call), and it cannot apply to an integer-returning cells at all — `_mx_pow` returns a `double`, which Cython refuses to assign to a `long long`, so a currently-working model would stop compiling.

It would also be inconsistent on its own: `**` would be safe while `*` next door still wrapped, which invites the assumption that integer arithmetic is safe generally.

## Where this leaves it

The two mitigations are complementary rather than alternatives — `overflowcheck` covers `+ - * <<` but not `**`; the pow rewrite covers `**` but not the rest — so closing the whole surface for double-returning cells would mean both, and the `abs()` build break would have to be resolved (or reported upstream) first. Whether that is worth it depends on how plausible you think a >2^63 intermediate is in a real model. Filing it so the decision is at least recorded.

Measured on Windows 11, Python 3.13.9, Cython 3.2.4, modelx 0.33.0, MSVC 19.37.32822, modelx-cython at 0f3e564.
